//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIGameClientTourist.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIGameClientTourist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si, deseo comprar esta propiedad.
        /// </summary>
        public static string AcceptPurchase_Button {
            get {
                return ResourceManager.GetString("AcceptPurchase-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A agregar:.
        /// </summary>
        public static string Add_Label {
            get {
                return ResourceManager.GetString("Add-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar edificio.
        /// </summary>
        public static string AddBuilding_Label {
            get {
                return ResourceManager.GetString("AddBuilding-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar Casa.
        /// </summary>
        public static string AddHouse {
            get {
                return ResourceManager.GetString("AddHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se ha enviado correctamente la solicitud de amistad.
        /// </summary>
        public static string AlertConfirmationSendFriendRequest_Label {
            get {
                return ResourceManager.GetString("AlertConfirmationSendFriendRequest-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya se ha enviado previamente una solicitud de amistad a este usuario.
        /// </summary>
        public static string AlertExistingRequest_Label {
            get {
                return ResourceManager.GetString("AlertExistingRequest-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de amistad no se pudo enviar. El jugador al cual le mandaste una solicitud, no existe.
        /// </summary>
        public static string AlertExistingUser_Label {
            get {
                return ResourceManager.GetString("AlertExistingUser-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor, ingrese un código de partida válido.
        /// </summary>
        public static string AlertInvalidCode_Label {
            get {
                return ResourceManager.GetString("AlertInvalidCode-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud de amistad no se pudo enviar. El jugador al cual le mandaste una solicitud, ya es tu amigo.
        /// </summary>
        public static string AlreadyExistingAmigoAlert_Label {
            get {
                return ResourceManager.GetString("AlreadyExistingAmigoAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, la partida ya ha comenzado..
        /// </summary>
        public static string AlreadyStartedAlert_Label {
            get {
                return ResourceManager.GetString("AlreadyStartedAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Subasta.
        /// </summary>
        public static string Auction_Label {
            get {
                return ResourceManager.GetString("Auction-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi Oferta.
        /// </summary>
        public static string Bid_Label {
            get {
                return ResourceManager.GetString("Bid-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comprar.
        /// </summary>
        public static string Buy_Button {
            get {
                return ResourceManager.GetString("Buy-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea comprar esta propiedad?.
        /// </summary>
        public static string BuyPropertie_Label {
            get {
                return ResourceManager.GetString("BuyPropertie-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Desea comprar esta propiedad?.
        /// </summary>
        public static string BuyProperty_Label {
            get {
                return ResourceManager.GetString("BuyProperty-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string Cancel_Button {
            get {
                return ResourceManager.GetString("Cancel-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Escoger pieza.
        /// </summary>
        public static string ChosePlayer_Label {
            get {
                return ResourceManager.GetString("ChosePlayer-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Close_Button {
            get {
                return ResourceManager.GetString("Close-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reanudar partida.
        /// </summary>
        public static string Continue_Button {
            get {
                return ResourceManager.GetString("Continue-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continuar.
        /// </summary>
        public static string ContinueChoice_button {
            get {
                return ResourceManager.GetString("ContinueChoice-button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contenido copiado al portapapeles.
        /// </summary>
        public static string CopyConfirmationAlert_Label {
            get {
                return ResourceManager.GetString("CopyConfirmationAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Costo de la propiedad.
        /// </summary>
        public static string CostRent_Label {
            get {
                return ResourceManager.GetString("CostRent-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Partida.
        /// </summary>
        public static string CreateGame_Button {
            get {
                return ResourceManager.GetString("CreateGame-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        public static string Date_Label {
            get {
                return ResourceManager.GetString("Date-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descripción: .
        /// </summary>
        public static string Description_Label {
            get {
                return ResourceManager.GetString("Description-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Perfil.
        /// </summary>
        public static string Edit_Button {
            get {
                return ResourceManager.GetString("Edit-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elija una figura.
        /// </summary>
        public static string ElijaFigura_Label {
            get {
                return ResourceManager.GetString("ElijaFigura-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Email_label {
            get {
                return ResourceManager.GetString("Email-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a yusgus@gmail.com.
        /// </summary>
        public static string eMail_txt {
            get {
                return ResourceManager.GetString("eMail-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta Evento.
        /// </summary>
        public static string EventCard_Label {
            get {
                return ResourceManager.GetString("EventCard-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir.
        /// </summary>
        public static string Exit_Button {
            get {
                return ResourceManager.GetString("Exit-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de la partida.
        /// </summary>
        public static string ExitGame_Button {
            get {
                return ResourceManager.GetString("ExitGame-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string Friends_Button {
            get {
                return ResourceManager.GetString("Friends-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string FriendshipRequests_Label {
            get {
                return ResourceManager.GetString("FriendshipRequests-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de amigos.
        /// </summary>
        public static string FriendsList_Label {
            get {
                return ResourceManager.GetString("FriendsList-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo siento, la partida se encuentra completa en este momento..
        /// </summary>
        public static string FullLineItemAlert_Label {
            get {
                return ResourceManager.GetString("FullLineItemAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de la partida.
        /// </summary>
        public static string GameCode_Label {
            get {
                return ResourceManager.GetString("GameCode-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida no encontrada, verifique su codigo por favor..
        /// </summary>
        public static string GameNoFound_Label {
            get {
                return ResourceManager.GetString("GameNoFound-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string GuestGame_Button {
            get {
                return ResourceManager.GetString("GuestGame-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prueba antes de registrarte.
        /// </summary>
        public static string GuestLogin_Label {
            get {
                return ResourceManager.GetString("GuestLogin-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID.
        /// </summary>
        public static string ID_label {
            get {
                return ResourceManager.GetString("ID-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo invalido,  verifique su codigo por favor..
        /// </summary>
        public static string InvalideGameCode_Label {
            get {
                return ResourceManager.GetString("InvalideGameCode-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string Invite_Button {
            get {
                return ResourceManager.GetString("Invite-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Codigo de la partida.
        /// </summary>
        public static string ItemCode_Label {
            get {
                return ResourceManager.GetString("ItemCode-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partida no encontrada. Verifique que el código sea correcto o que la partida exista..
        /// </summary>
        public static string ItemNotFoundAlert_Label {
            get {
                return ResourceManager.GetString("ItemNotFoundAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string JoinGame_Button {
            get {
                return ResourceManager.GetString("JoinGame-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse Partida.
        /// </summary>
        public static string JoinGame_Label {
            get {
                return ResourceManager.GetString("JoinGame-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string KickPlayer_Button {
            get {
                return ResourceManager.GetString("KickPlayer-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        public static string LanguageEnglish_Label {
            get {
                return ResourceManager.GetString("LanguageEnglish-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        public static string LanguageSpanish_Label {
            get {
                return ResourceManager.GetString("LanguageSpanish-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguaje.
        /// </summary>
        public static string Languaje_Label {
            get {
                return ResourceManager.GetString("Languaje-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sessión.
        /// </summary>
        public static string Logout_Button {
            get {
                return ResourceManager.GetString("Logout-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dinero.
        /// </summary>
        public static string Money_Label {
            get {
                return ResourceManager.GetString("Money-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Volumen.
        /// </summary>
        public static string Music_Label {
            get {
                return ResourceManager.GetString("Music-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Musica: .
        /// </summary>
        public static string MusicTitle_Label {
            get {
                return ResourceManager.GetString("MusicTitle-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mis Propiedades.
        /// </summary>
        public static string MyProperties_Label {
            get {
                return ResourceManager.GetString("MyProperties-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Name_Label {
            get {
                return ResourceManager.GetString("Name-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KingsLayer123.
        /// </summary>
        public static string Name_txt {
            get {
                return ResourceManager.GetString("Name-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre usuario.
        /// </summary>
        public static string NickName_Label {
            get {
                return ResourceManager.GetString("NickName-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a KingsLayer123.
        /// </summary>
        public static string NickName_txt {
            get {
                return ResourceManager.GetString("NickName-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string No_Button {
            get {
                return ResourceManager.GetString("No-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sin casas: .
        /// </summary>
        public static string NoHouses_Label {
            get {
                return ResourceManager.GetString("NoHouses-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya tiene edificio.
        /// </summary>
        public static string NumberBuilding {
            get {
                return ResourceManager.GetString("NumberBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualmente tiene X casas.
        /// </summary>
        public static string NumberHouses {
            get {
                return ResourceManager.GetString("NumberHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string OK_Button {
            get {
                return ResourceManager.GetString("OK-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a myiss32782ERSd10210.
        /// </summary>
        public static string Password_txt {
            get {
                return ResourceManager.GetString("Password-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pausa.
        /// </summary>
        public static string Pause_Label {
            get {
                return ResourceManager.GetString("Pause-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar Partida.
        /// </summary>
        public static string Play_Button {
            get {
                return ResourceManager.GetString("Play-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string Player_Label {
            get {
                return ResourceManager.GetString("Player-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores conectados a la partida.
        /// </summary>
        public static string PlayerList_Label {
            get {
                return ResourceManager.GetString("PlayerList-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Players_Label {
            get {
                return ResourceManager.GetString("Players-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores unidos a la partida.
        /// </summary>
        public static string PlayersUnitedMatch_Label {
            get {
                return ResourceManager.GetString("PlayersUnitedMatch-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prisión o Carcel.
        /// </summary>
        public static string PrisionOrCarcel_Label {
            get {
                return ResourceManager.GetString("PrisionOrCarcel-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string Profile_Button {
            get {
                return ResourceManager.GetString("Profile-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Titulo de la Propiedad.
        /// </summary>
        public static string PropertyTitle {
            get {
                return ResourceManager.GetString("PropertyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pujar.
        /// </summary>
        public static string Pull_Button {
            get {
                return ResourceManager.GetString("Pull-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si un jugador posee TODAS las Propiedades de un solo color , el precio del alquiler se DUPLICA en las propiedades&amp;#xD;&amp;#xA;SIN EDIFICAR de ese grupo.
        /// </summary>
        public static string PurchaseDescription_Label {
            get {
                return ResourceManager.GetString("PurchaseDescription-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar Contraseña.
        /// </summary>
        public static string RecoverPassword_Label {
            get {
                return ResourceManager.GetString("RecoverPassword-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Register_Button {
            get {
                return ResourceManager.GetString("Register-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar Usuario.
        /// </summary>
        public static string RegisterUserTitle_Label {
            get {
                return ResourceManager.GetString("RegisterUserTitle-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string Reject_Button {
            get {
                return ResourceManager.GetString("Reject-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No, no quiero comprar esta propiedad.
        /// </summary>
        public static string RejectPurchase_Label {
            get {
                return ResourceManager.GetString("RejectPurchase-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Renta.
        /// </summary>
        public static string Rent_Label {
            get {
                return ResourceManager.GetString("Rent-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a myiss32782ERSd10210.
        /// </summary>
        public static string RepitPassword_txt {
            get {
                return ResourceManager.GetString("RepitPassword-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirar Dados.
        /// </summary>
        public static string Roll_Button {
            get {
                return ResourceManager.GetString("Roll-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Save_Button {
            get {
                return ResourceManager.GetString("Save-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar nuevo amigo.
        /// </summary>
        public static string SearchFriend_Label {
            get {
                return ResourceManager.GetString("SearchFriend-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar Partida.
        /// </summary>
        public static string SearchGame_Button {
            get {
                return ResourceManager.GetString("SearchGame-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Correo.
        /// </summary>
        public static string SendEMail_Button {
            get {
                return ResourceManager.GetString("SendEMail-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Solicitud.
        /// </summary>
        public static string SendRequest_Button {
            get {
                return ResourceManager.GetString("SendRequest-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones.
        /// </summary>
        public static string Settings_Button {
            get {
                return ResourceManager.GetString("Settings-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones.
        /// </summary>
        public static string Settings_Label {
            get {
                return ResourceManager.GetString("Settings-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Partida.
        /// </summary>
        public static string Start_Button {
            get {
                return ResourceManager.GetString("Start-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resultado de la partida.
        /// </summary>
        public static string Status_Label {
            get {
                return ResourceManager.GetString("Status-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exito.
        /// </summary>
        public static string SuccessConfirmationAlert_Label {
            get {
                return ResourceManager.GetString("SuccessConfirmationAlert-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turista Lugares Fantasticos.
        /// </summary>
        public static string TitleNameGameName_Label {
            get {
                return ResourceManager.GetString("TitleNameGameName-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Max. Oferta.
        /// </summary>
        public static string TopOffer_Label {
            get {
                return ResourceManager.GetString("TopOffer-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total a pagar es: $.
        /// </summary>
        public static string TotalCost {
            get {
                return ResourceManager.GetString("TotalCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno.
        /// </summary>
        public static string Turn_Label {
            get {
                return ResourceManager.GetString("Turn-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario no encontrado.
        /// </summary>
        public static string UnexistingPlayer_Label {
            get {
                return ResourceManager.GetString("UnexistingPlayer-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar Mensaje.
        /// </summary>
        public static string Verify_Button {
            get {
                return ResourceManager.GetString("Verify-Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el codigo.
        /// </summary>
        public static string VerifyCode_label {
            get {
                return ResourceManager.GetString("VerifyCode-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 102989018302.00.
        /// </summary>
        public static string VerifyCode_txt {
            get {
                return ResourceManager.GetString("VerifyCode-txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar contraseña.
        /// </summary>
        public static string verifyPassword_Label {
            get {
                return ResourceManager.GetString("verifyPassword-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Espere por favor…....
        /// </summary>
        public static string Wait_Label {
            get {
                return ResourceManager.GetString("Wait-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Porcentaje de victorias.
        /// </summary>
        public static string Winrate_Label {
            get {
                return ResourceManager.GetString("Winrate-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con 1 casa: .
        /// </summary>
        public static string With1House {
            get {
                return ResourceManager.GetString("With1House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con 2 casas:.
        /// </summary>
        public static string With2Houses {
            get {
                return ResourceManager.GetString("With2Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con 3 casas:.
        /// </summary>
        public static string With3Houses {
            get {
                return ResourceManager.GetString("With3Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con 4 casas:.
        /// </summary>
        public static string With4Houses {
            get {
                return ResourceManager.GetString("With4Houses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con edificio: .
        /// </summary>
        public static string WithBuilding {
            get {
                return ResourceManager.GetString("WithBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el codigo de la partida.
        /// </summary>
        public static string WriteGameCode_Label {
            get {
                return ResourceManager.GetString("WriteGameCode-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario incorrecto.
        /// </summary>
        public static string WrongNickName_Label {
            get {
                return ResourceManager.GetString("WrongNickName-Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña incorrecta, verifiquela por favor.
        /// </summary>
        public static string WrongPassword_label {
            get {
                return ResourceManager.GetString("WrongPassword-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si.
        /// </summary>
        public static string Yes_Button {
            get {
                return ResourceManager.GetString("Yes-Button", resourceCulture);
            }
        }
    }
}
